services:
  - type: web
    name: motrix-api
    runtime: docker
    plan: free
    region: ohio
    branch: main
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /up
    autoDeployTrigger: commit
    envVars:
      - key: APP_NAME
        value: MOTRIX
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: public
      - key: CORS_ALLOWED_ORIGINS
        value: https://motrix-nu.vercel.app
      - key: BROADCAST_CONNECTION
        value: reverb
      - key: REVERB_APP_ID
        value: motrix
      - key: REVERB_APP_KEY
        value: motrix-prod-key
      - key: REVERB_APP_SECRET
        sync: false
      - key: REVERB_HOST
        value: motrix-reverb.onrender.com
      - key: REVERB_PORT
        value: "443"
      - key: REVERB_SCHEME
        value: https

  - type: web
    name: motrix-reverb
    runtime: docker
    plan: free
    region: ohio
    branch: main
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    dockerCommand: php artisan reverb:start --host=0.0.0.0 --port=10000
    autoDeployTrigger: commit
    envVars:
      - key: APP_NAME
        value: MOTRIX-Reverb
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: BROADCAST_CONNECTION
        value: reverb
      - key: REVERB_APP_ID
        value: motrix
      - key: REVERB_APP_KEY
        value: motrix-prod-key
      - key: REVERB_APP_SECRET
        sync: false
      - key: REVERB_SERVER_HOST
        value: 0.0.0.0
      - key: REVERB_SERVER_PORT
        value: "10000"
      - key: REVERB_HOST
        value: motrix-reverb.onrender.com
      - key: REVERB_PORT
        value: "443"
      - key: REVERB_SCHEME
        value: https
